version: '1.0'

services:
  mutant_db:
    container_name: 'mutant_challenge'
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mutant_db:/var/lib/postgresql/data
    command: postgres -p ${DB_PORT}
volumes:
  mutant_db:
    driver: local
